<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MufrodatSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('mufrodats')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $data = [
            // IX Bab 1 - Ra\'s as-Sanah al-Hijriyyah (Awal Tahun Hijriyah)
            ['arab' => 'أَرَادَ', 'latin' => 'arāda', 'arti' => 'ingin', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يُرِيْدُ', 'latin' => 'yurīdu', 'arti' => 'ingin', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'هَاجَرَ', 'latin' => 'hājara', 'arti' => 'berpindah', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يُهَاجِرُ', 'latin' => 'yuhājiru', 'arti' => 'berpindah', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'مَنَعَ', 'latin' => 'mana\'a', 'arti' => 'mencegah', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَمْنَعُ', 'latin' => 'yamna\'u', 'arti' => 'mencegah', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'قَتَلَ', 'latin' => 'qatala', 'arti' => 'membunuh', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَقْتُلُ', 'latin' => 'yaqtulu', 'arti' => 'membunuh', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'اِسْتَقْبَلَ', 'latin' => 'istaqbala', 'arti' => 'menyambut', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَسْتَقْبِلُ', 'latin' => 'yastaqbilu', 'arti' => 'menyambut', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'تَآخَى', 'latin' => 'tākhā', 'arti' => 'bersaudara', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَتَآخَى', 'latin' => 'yatākhā', 'arti' => 'bersaudara', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'صَارَ', 'latin' => 'shāra', 'arti' => 'menjadi', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَصِيْرُ', 'latin' => 'yashīru', 'arti' => 'menjadi', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'تَشَارَكَ', 'latin' => 'tasyāraka', 'arti' => 'bersama-sama', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَتَشَارَكُ', 'latin' => 'yatasyāraku', 'arti' => 'bersama-sama', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'هَنَّأَ', 'latin' => 'hanna\'a', 'arti' => 'mengucapkan selamat', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يُهَنِّئُ', 'latin' => 'yuhanni\'u', 'arti' => 'mengucapkan selamat', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'نَجَّى', 'latin' => 'najjā', 'arti' => 'menyelamatkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يُنَجِّي', 'latin' => 'yunajjī', 'arti' => 'menyelamatkan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'اِنْتَشَرَ', 'latin' => 'intasyara', 'arti' => 'tersebar', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَنْتَشِرُ', 'latin' => 'yantasyiru', 'arti' => 'tersebar', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'تَرَكَ', 'latin' => 'taraka', 'arti' => 'meninggalkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَتْرُكُ', 'latin' => 'yatruku', 'arti' => 'meninggalkan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'وَضَعَ', 'latin' => 'wadha\'a', 'arti' => 'membuat/meletakkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَضَعُ', 'latin' => 'yadha\'u', 'arti' => 'membuat/meletakkan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'وَصَلَ', 'latin' => 'washala', 'arti' => 'sampai', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَصِلُ', 'latin' => 'yashilu', 'arti' => 'sampai', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'اِحْتَفَلَ', 'latin' => 'iḥtafala', 'arti' => 'merayakan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَحْتَفِلُ', 'latin' => 'yaḥtafilu', 'arti' => 'merayakan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'سَكَنَ', 'latin' => 'sakana', 'arti' => 'bertempat tinggal', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَسْكُنُ', 'latin' => 'yaskunu', 'arti' => 'bertempat tinggal', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'قَالَ', 'latin' => 'qāla', 'arti' => 'berkata', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَقُوْلُ', 'latin' => 'yaqūlu', 'arti' => 'berkata', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'قَبْلَ ثَلاَثَةِ أَيَّامٍ', 'latin' => 'qabla tsalaatsati ayyaam', 'arti' => 'tiga hari yang lalu', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'يَوْمَ الْأَحَدِ الْمَاضِي', 'latin' => 'yaum al-aḥad al-mādhī', 'arti' => 'hari Ahad yang lalu', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'فِي الْأُسْبُوْعِ الْمَاضِي', 'latin' => 'fil usbū\' al-mādhī', 'arti' => 'pada minggu yang lalu', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'فِي الشَّهْرِ الْمَاضِي', 'latin' => 'fisy syahr al-mādhī', 'arti' => 'pada bulan yang lalu', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'فِي السَّنَةِ الْمَاضِيَةِ', 'latin' => 'fis sanah al-mādhiyah', 'arti' => 'pada tahun yang lalu', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'صَبَاحَ الْيَوْمِ', 'latin' => 'shabāḥal yaum', 'arti' => 'tadi pagi', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'فِي الْبَارِحَةِ', 'latin' => 'fil bāriḥah', 'arti' => 'tadi malam', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'قَبْلَ الْأَمْسِ', 'latin' => 'qablal amsi', 'arti' => 'kemarin lusa', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'قَبْلَ الْأُسْبُوْعِ', 'latin' => 'qablal usbū\'', 'arti' => 'sebelum minggu ini', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 1],
            ['arab' => 'أَمْسِ', 'latin' => 'amsi', 'arti' => 'kemarin', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 1],
            // IX Bab 2 - Al-Haflu bi Dzikra Maulidir Rasul SAW (Perayaan Maulid Nabi)
            ['arab' => 'أَقَامَ', 'latin' => 'aqāma', 'arti' => 'menyelenggarakan (mendirikan)', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يُقِيْمُ', 'latin' => 'yuqīmu', 'arti' => 'menyelenggarakan (mendirikan)', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'وَلَدَ', 'latin' => 'walada', 'arti' => 'melahirkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يَلِدُ', 'latin' => 'yalidu', 'arti' => 'melahirkan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'تُوُفِّيَ', 'latin' => 'tuwuffiya', 'arti' => 'wafat', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'مَكَثَ', 'latin' => 'makatsa', 'arti' => 'tinggal (menetap)', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يَمْكُثُ', 'latin' => 'yamkutsu', 'arti' => 'tinggal (menetap)', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'أَوْصَى', 'latin' => 'awshā', 'arti' => 'berpesan (berwasiat)', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يُوْصِي', 'latin' => 'yūshī', 'arti' => 'berpesan (berwasiat)', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'تَزَوَّجَ', 'latin' => 'tazawwaja', 'arti' => 'menikahi', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يَتَزَوَّجُ', 'latin' => 'yatazawwaju', 'arti' => 'menikahi', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'بَعَثَ', 'latin' => 'ba\'atsa', 'arti' => 'mengutus', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يَبْعَثُ', 'latin' => 'yab\'atsu', 'arti' => 'mengutus', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'حَمَى', 'latin' => 'hamā', 'arti' => 'melindungi', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يَحْمِي', 'latin' => 'yahmī', 'arti' => 'melindungi', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'أَلْقَى', 'latin' => 'alqā', 'arti' => 'menyampaikan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يُلْقِي', 'latin' => 'yulqī', 'arti' => 'menyampaikan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'صَدَّقَ', 'latin' => 'shaddaqa', 'arti' => 'membenarkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يُصَدِّقُ', 'latin' => 'yushaddiqu', 'arti' => 'membenarkan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'أَسْرَى', 'latin' => 'asrā', 'arti' => 'mengisra\'kan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يُسْرِي', 'latin' => 'yusrī', 'arti' => 'mengisra\'kan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'زَيَّنَ', 'latin' => 'zayyana', 'arti' => 'menghiasi', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يُزَيِّنُ', 'latin' => 'yuzayyinu', 'arti' => 'menghiasi', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'نَظَّمَ', 'latin' => 'nazhzhama', 'arti' => 'mengatur', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يُنَظِّمُ', 'latin' => 'yunazhzhimu', 'arti' => 'mengatur', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'وَزَّعَ', 'latin' => 'wazza\'a', 'arti' => 'membagikan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يُوَزِّعُ', 'latin' => 'yuwazzi\'u', 'arti' => 'membagikan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'اِجْتَمَعَ', 'latin' => 'ijtama\'a', 'arti' => 'berkumpul', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يَجْتَمِعُ', 'latin' => 'yajtami\'u', 'arti' => 'berkumpul', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'اِسْتَمَعَ', 'latin' => 'istama\'a', 'arti' => 'mendengarkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'يَسْتَمِعُ', 'latin' => 'yastami\'u', 'arti' => 'mendengarkan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'اِهْتِمَامٌ', 'latin' => 'ihtimaam', 'arti' => 'perhatian', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'مَوْضُوْعٌ', 'latin' => 'maudhuu\'', 'arti' => 'judul', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'سِيْرَةٌ', 'latin' => 'siirah', 'arti' => 'jalan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'رِسَالَةٌ', 'latin' => 'risaalah', 'arti' => 'surat', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'مَدْرَسَةٌ', 'latin' => 'madrasah', 'arti' => 'sekolah', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'بَعْضٌ', 'latin' => 'ba\'dh', 'arti' => 'sebagian', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'مَكْتَبٌ', 'latin' => 'maktab', 'arti' => 'kantor/meja', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'أَذَى', 'latin' => 'adzaa', 'arti' => 'cacian', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'لَجْنَةٌ', 'latin' => 'lajnah', 'arti' => 'panitia', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'عُضْوٌ', 'latin' => '\'udhw', 'arti' => 'anggota', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'تَشْكِيْلٌ', 'latin' => 'tasykiil', 'arti' => 'pemecahan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 2],
            ['arab' => 'ذِكْرَى', 'latin' => 'dzikraa', 'arti' => 'peringatan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 2],
            // IX Bab 3 - Nuzuulul Qur\'an (Turunnya Al-Qur\'an)
            ['arab' => 'خَلَقَ', 'latin' => 'khalaqa', 'arti' => 'menciptakan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يَخْلُقُ', 'latin' => 'yakhluqu', 'arti' => 'menciptakan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'خَلْقًا', 'latin' => 'khalqan', 'arti' => 'menciptakan', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'نَزَلَ', 'latin' => 'nazala', 'arti' => 'turun', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يَنْزِلُ', 'latin' => 'yanzilu', 'arti' => 'turun', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'نُزُوْلًا', 'latin' => 'nuzuulan', 'arti' => 'turun', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'عَلِمَ', 'latin' => '\'alima', 'arti' => 'mengetahui', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يَعْلَمُ', 'latin' => 'ya\'lamu', 'arti' => 'mengetahui', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'عِلْمًا', 'latin' => '\'ilman', 'arti' => 'mengetahui', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'سَمَّى', 'latin' => 'sammā', 'arti' => 'menamai', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يُسَمِّي', 'latin' => 'yusammī', 'arti' => 'menamai', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'تَسْمِيَةً', 'latin' => 'tasmiyatan', 'arti' => 'menamai', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'أَنْزَلَ', 'latin' => 'anzala', 'arti' => 'menurunkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يُنْزِلُ', 'latin' => 'yunzilu', 'arti' => 'menurunkan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'إِنْزَالًا', 'latin' => 'inzaalan', 'arti' => 'menurunkan', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'نَزَّلَ', 'latin' => 'nazzala', 'arti' => 'menurunkan (berangsur-angsur)', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يُنَزِّلُ', 'latin' => 'yunazzilu', 'arti' => 'menurunkan (berangsur-angsur)', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'تَنْزِيْلًا', 'latin' => 'tanziilan', 'arti' => 'menurunkan (berangsur-angsur)', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'عَلَّمَ', 'latin' => '\'allama', 'arti' => 'mengajar', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يُعَلِّمُ', 'latin' => 'yu\'allimu', 'arti' => 'mengajar', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'تَعْلِيْمًا', 'latin' => 'ta\'liiman', 'arti' => 'mengajar', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'تَعَبَّدَ', 'latin' => 'ta\'abbada', 'arti' => 'beribadat', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يَتَعَبَّدُ', 'latin' => 'yata\'abbadu', 'arti' => 'beribadat', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'تَعَبُّدًا', 'latin' => 'ta\'abbudan', 'arti' => 'beribadat', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'اَلْمَرَّةُ الثَّالِثَةِ', 'latin' => 'al-marratu ats-tsaalitsah', 'arti' => 'ketiga kali', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'مَا أَنَا بِقَارِئٍ', 'latin' => 'maa ana biqaari\'in', 'arti' => 'saya tidak bisa membaca', 'jenis' => 'Mubtada - Khabar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'تِلاَوَةٌ', 'latin' => 'tilaawah', 'arti' => 'membaca', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'دُسْتُوْرٌ', 'latin' => 'dustuur', 'arti' => 'undang-undang', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'حَيَاةُ الْمُسْلِمِيْنَ', 'latin' => 'hayaatul muslimiin', 'arti' => 'kehidupan umat Islam', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'مُنَجَّمًا', 'latin' => 'munajjaman', 'arti' => 'berangsur-angsur', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'دَفْعَةً وَاحِدَةً', 'latin' => 'daf\'atan waahidatan', 'arti' => 'sekaligus', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'كَلاَمُ اللهِ', 'latin' => 'kalaamullah', 'arti' => 'firman Allah', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'تَعْلِيْمٌ', 'latin' => 'ta\'liim', 'arti' => 'belajar', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'سُوْرَةٌ', 'latin' => 'suurah', 'arti' => 'surat', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'أُمِّيٌّ', 'latin' => 'ummiyy', 'arti' => 'belum mengenal bacaan dan tulisan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'كَبَّرَ', 'latin' => 'kabbara', 'arti' => 'mengucapkan takbir', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يُكَبِّرُ', 'latin' => 'yukabbiru', 'arti' => 'mengucapkan takbir', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'تَكْبِيْرًا', 'latin' => 'takbiiran', 'arti' => 'mengucapkan takbir', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'اِرْتَبَطَ', 'latin' => 'irtabatha', 'arti' => 'berhubungan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يَرْتَبِطُ', 'latin' => 'yartabithu', 'arti' => 'berhubungan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'اِرْتِبَاطًا', 'latin' => 'irtibaathan', 'arti' => 'berhubungan', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'اِجْتِمَاعًا', 'latin' => 'ijtimaa\'an', 'arti' => 'berkumpul, rapat', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'اِشْتَرَى', 'latin' => 'isytaraa', 'arti' => 'membeli', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يَشْتَرِي', 'latin' => 'yasytarii', 'arti' => 'membeli', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'شِرَاءً', 'latin' => 'syiraa\'an', 'arti' => 'membeli', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'تَعَطَّلَ', 'latin' => 'ta\'aththala', 'arti' => 'libur', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يَتَعَطَّلُ', 'latin' => 'yata\'aththalu', 'arti' => 'libur', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'تَعَطُّلًا', 'latin' => 'ta\'aththulan', 'arti' => 'libur', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'ذَبَحَ', 'latin' => 'dzabaha', 'arti' => 'menyembelih', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يَذْبَحُ', 'latin' => 'yadzbahu', 'arti' => 'menyembelih', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'ذَبْحًا', 'latin' => 'dzabhan', 'arti' => 'menyembelih', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'فَرِحَ', 'latin' => 'fariha', 'arti' => 'riang gembira', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يَفْرَحُ', 'latin' => 'yafrahu', 'arti' => 'riang gembira', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'فَرَحًا', 'latin' => 'farahan', 'arti' => 'riang gembira', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'بَاتَ', 'latin' => 'baata', 'arti' => 'menginap', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يَبِيْتُ', 'latin' => 'yabiitu', 'arti' => 'menginap', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'مَبِيْتًا', 'latin' => 'mabiitan', 'arti' => 'menginap', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'أَعْطَى', 'latin' => 'a\'thaa', 'arti' => 'memberi', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يُعْطِي', 'latin' => 'yu\'thii', 'arti' => 'memberi', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'عَطَاءً', 'latin' => '\'athaa\'an', 'arti' => 'memberi', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'أَقْفَلَ', 'latin' => 'aqfala', 'arti' => 'menutup, mengunci', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'يُقْفِلُ', 'latin' => 'yuqfilu', 'arti' => 'menutup, mengunci', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 3],
            ['arab' => 'إِقْفَالًا', 'latin' => 'iqfaalan', 'arti' => 'menutup, mengunci', 'jenis' => 'Masdar', 'kelas' => 'IX', 'bab' => 3],
            // IX Bab 4 - Jamal ath-Thabi\'ah (Keindahan Alam)
            ['arab' => 'رَحَلَ', 'latin' => 'raḥala', 'arti' => 'pergi', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'يَرْحَلُ', 'latin' => 'yarḥalu', 'arti' => 'pergi', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'اِسْتَغْرَقَ', 'latin' => 'istaghraqa', 'arti' => 'menghabiskan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'يَسْتَغْرِقُ', 'latin' => 'yastaghriqu', 'arti' => 'menghabiskan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'قَطَفَ', 'latin' => 'qathafa', 'arti' => 'memetik', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'يَقْطُفُ', 'latin' => 'yaqthufu', 'arti' => 'memetik', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'اِسْتَأْذَنَ', 'latin' => 'ista\'dzana', 'arti' => 'meminta izin', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'يَسْتَأْذِنُ', 'latin' => 'yasta\'dzinu', 'arti' => 'meminta izin', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'أَتَى', 'latin' => 'atā', 'arti' => 'datang/tiba', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'يَأْتِي', 'latin' => 'ya\'tī', 'arti' => 'datang/tiba', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'تَمَتَّعَ', 'latin' => 'tamatta\'a', 'arti' => 'menikmati', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'يَتَمَتَّعُ', 'latin' => 'yatamatta\'u', 'arti' => 'menikmati', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'سَارَ', 'latin' => 'sāra', 'arti' => 'berjalan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'يَسِيْرُ', 'latin' => 'yasīru', 'arti' => 'berjalan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'طَرَدَ', 'latin' => 'tharada', 'arti' => 'mengusir', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'يَطْرُدُ', 'latin' => 'yathrudu', 'arti' => 'mengusir', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'شَارَكَ', 'latin' => 'syāraka', 'arti' => 'menyertai', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'يُشَارِكُ', 'latin' => 'yusyāriku', 'arti' => 'menyertai', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'يَصِلُ إِلَى', 'latin' => 'yashilu ilā', 'arti' => 'sampai', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'زَرَعَ', 'latin' => 'zara\'a', 'arti' => 'menanam', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'يَزْرَعُ', 'latin' => 'yazra\'u', 'arti' => 'menanam', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'تَذَكَّرَ', 'latin' => 'tadzakkara', 'arti' => 'teringat', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'يَتَذَكَّرُ', 'latin' => 'yatadzakkaru', 'arti' => 'teringat', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'الْأَشْجَارُ الْخَضْرَاءُ', 'latin' => 'al-asyjārul khadhrā\'', 'arti' => 'pepohonan hijau', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'الْجَنُوْبُ', 'latin' => 'al-janūb', 'arti' => 'selatan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'الرِّمَالُ الْبَيْضَاءُ', 'latin' => 'ar-rimālul baidhā\'', 'arti' => 'pasir putih', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'مَوْجٌ', 'latin' => 'mauj', 'arti' => 'ombak', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'صَيَّادُ السَّمَكِ', 'latin' => 'shayyādus samak', 'arti' => 'nelayan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'مَأْكُوْلَاتٌ', 'latin' => 'ma\'kūlāt', 'arti' => 'makanan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'لُعْبَةٌ', 'latin' => 'lu\'bah', 'arti' => 'mainan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'الْبَطَاطِسُ', 'latin' => 'al-bathāthis', 'arti' => 'kentang', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'الْكُرُنْبُ', 'latin' => 'al-kurunb', 'arti' => 'kobis', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'بِكُلِّ سُرُوْرٍ', 'latin' => 'bikulli surūr', 'arti' => 'dengan senang hati', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'مَا عِنْدِي', 'latin' => 'mā \'indī', 'arti' => 'saya tidak punya', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'الْحَبَّةُ', 'latin' => 'al-habbah', 'arti' => 'biji-bijian', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'أَيَّامُ الْعُطْلَةِ', 'latin' => 'ayyāmul \'uthlah', 'arti' => 'hari libur', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'مَنْطَقَةٌ', 'latin' => 'manthaqah', 'arti' => 'daerah', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'حَدَائِقُ الشَّايِ', 'latin' => 'hadā\'iqusy syāy', 'arti' => 'kebun teh', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'الْمَنَاظِرُ الطَّبِيْعِيَّةُ', 'latin' => 'al-manādzirut thabī\'iyyah', 'arti' => 'pemandangan alam', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'الْفَلَّاحُوْنَ', 'latin' => 'al-fallāḥūn', 'arti' => 'para petani', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'الْبَذْرُ', 'latin' => 'al-badzr', 'arti' => 'benih', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'أَوْرَاقُ الشَّايِ', 'latin' => 'awrāqusy syāy', 'arti' => 'daun teh', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'الطَّيْرُ', 'latin' => 'ath-thayr', 'arti' => 'burung', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'الْحَشَرَاتُ', 'latin' => 'al-hasyarāt', 'arti' => 'hama', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'خُطَّةُ الْعُطْلَةِ', 'latin' => 'khuthathul \'uthlah', 'arti' => 'rencana liburan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'أَثْنَاءَ الطَّرِيْقِ', 'latin' => 'atsnā\'a ath-tharīq', 'arti' => 'di tengah jalan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            ['arab' => 'حُقُوْلُ الْخَضْرَوَاتِ', 'latin' => 'huqūlul khadhrawāt', 'arti' => 'kebun sayuran', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 4],
            // IX Bab 5 - Khaliq al-\'Alam (Pencipta Alam)
            ['arab' => 'شَعَرَ', 'latin' => 'sya\'ara', 'arti' => 'merasa', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يَشْعُرُ', 'latin' => 'yasy\'uru', 'arti' => 'merasa', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'أَحَبَّ', 'latin' => 'aḥabba', 'arti' => 'menyukai', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يُحِبُّ', 'latin' => 'yuḥibbu', 'arti' => 'menyukai', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'اِجْتَهَدَ', 'latin' => 'ijtahada', 'arti' => 'bersungguh-sungguh', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يَجْتَهِدُ', 'latin' => 'yajtahidu', 'arti' => 'bersungguh-sungguh', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'حَرَثَ', 'latin' => 'ḥaratsa', 'arti' => 'membajak', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يَحْرُثُ', 'latin' => 'yaḥrutsu', 'arti' => 'membajak', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'اِشْتَغَلَ', 'latin' => 'isytaghala', 'arti' => 'sibuk', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يَشْتَغِلُ', 'latin' => 'yasytaghilu', 'arti' => 'sibuk', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'عَاشَ', 'latin' => '\'āsya', 'arti' => 'hidup', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يَعِيْشُ', 'latin' => 'ya\'īsyu', 'arti' => 'hidup', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'اِسْتَرَاحَ', 'latin' => 'istarāḥa', 'arti' => 'istirahat', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يَسْتَرِيْحُ', 'latin' => 'yastarīḥu', 'arti' => 'istirahat', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'دَبَّرَ', 'latin' => 'dabbara', 'arti' => 'mengatur', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يُدَبِّرُ', 'latin' => 'yudabbiru', 'arti' => 'mengatur', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'قَدَّرَ', 'latin' => 'qaddara', 'arti' => 'menakdirkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يُقَدِّرُ', 'latin' => 'yuqaddiru', 'arti' => 'menakdirkan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'فَرَّقَ', 'latin' => 'farraqa', 'arti' => 'membedakan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يُفَرِّقُ', 'latin' => 'yufarriqu', 'arti' => 'membedakan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'اِسْتَمَرَّ', 'latin' => 'istamarra', 'arti' => 'melanjutkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يَسْتَمِرُّ', 'latin' => 'yastamirru', 'arti' => 'melanjutkan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'جَعَلَ', 'latin' => 'ja\'ala', 'arti' => 'menjadikan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يَجْعَلُ', 'latin' => 'yaj\'alu', 'arti' => 'menjadikan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'أَضَاءَ', 'latin' => 'adhā\'a', 'arti' => 'menyinari', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يُضِيْءُ', 'latin' => 'yudhī\'u', 'arti' => 'menyinari', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'أَنْبَتَ', 'latin' => 'anbata', 'arti' => 'menumbuhkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يُنْبِتُ', 'latin' => 'yunbitu', 'arti' => 'menumbuhkan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'اِنْتَظَرَ', 'latin' => 'intazhara', 'arti' => 'menunggu', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'يَنْتَظِرُ', 'latin' => 'yantazhiru', 'arti' => 'menunggu', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'جَاكِتَةٌ كَثِيْفَةٌ', 'latin' => 'jākitah katsīfah', 'arti' => 'jaket tebal', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'الْفَاكِهَةُ', 'latin' => 'al-fākihah', 'arti' => 'buah-buahan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'قِمَّةُ الْجَبَلِ', 'latin' => 'qimmatul jabal', 'arti' => 'puncak gunung', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'التَّعَاوُنُ', 'latin' => 'at-ta\'āwun', 'arti' => 'saling membantu', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'نِعْمَةٌ', 'latin' => 'ni\'mah', 'arti' => 'nikmat', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'الْإِبْدَاعُ', 'latin' => 'al-ibdā\'', 'arti' => 'penciptaan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'الْإِتْقَانُ', 'latin' => 'al-itqān', 'arti' => 'penyempurnaan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'الْكَوْنُ', 'latin' => 'al-kaun', 'arti' => 'alam', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'الزَّهْرَةُ', 'latin' => 'az-zahrah', 'arti' => 'bunga', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'الْجَوْهَرُ', 'latin' => 'al-jauhar', 'arti' => 'permata', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'الْمَزْرَعَةُ', 'latin' => 'al-mazra\'ah', 'arti' => 'sawah', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'بُرُوْدُ الْهَوَاءِ', 'latin' => 'burūdul hawā\'', 'arti' => 'sejuknya udara', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'الْحَيَاةُ', 'latin' => 'al-ḥayāh', 'arti' => 'kehidupan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'الشَّرُّ', 'latin' => 'asy-syarr', 'arti' => 'keburukan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'الْبَحْرُ', 'latin' => 'al-baḥr', 'arti' => 'laut', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'الرِّزْقُ', 'latin' => 'ar-rizq', 'arti' => 'rezeki', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'الْحَوَائِجُ الْيَوْمِيَّةُ', 'latin' => 'al-ḥawā\'ijul yaumiyyah', 'arti' => 'kebutuhan sehari-hari', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'مَصْدَرٌ', 'latin' => 'mashdar', 'arti' => 'sumber', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'نَشْكُرُ', 'latin' => 'nasykuru', 'arti' => 'mensyukuri', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'لِلنُّزْهَةِ', 'latin' => 'linnuzhah', 'arti' => 'piknik', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'سَفْحُ جَبَلٍ', 'latin' => 'safḥu jabal', 'arti' => 'lereng gunung', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            ['arab' => 'حَسَنًا', 'latin' => 'ḥasanan', 'arti' => 'baiklah', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 5],
            // IX Bab 6 - Al-Hifaadz \'ala al-Bi\'ah (Menjaga Lingkungan)
            ['arab' => 'أَفْسَدَ', 'latin' => 'afsada', 'arti' => 'merusak', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يُفْسِدُ', 'latin' => 'yufsidu', 'arti' => 'merusak', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'سَاعَدَ', 'latin' => 'sā\'ada', 'arti' => 'menolong', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يُسَاعِدُ', 'latin' => 'yusā\'idu', 'arti' => 'menolong', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'اِسْتَعَارَ', 'latin' => 'ista\'āra', 'arti' => 'meminjam', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يَسْتَعِيْرُ', 'latin' => 'yasta\'īru', 'arti' => 'meminjam', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'أَثَّرَ', 'latin' => 'atstsara', 'arti' => 'mempengaruhi', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يُؤَثِّرُ', 'latin' => 'yu\'atstsiru', 'arti' => 'mempengaruhi', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'أَهْمَلَ', 'latin' => 'ahmala', 'arti' => 'mengabaikan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يُهْمِلُ', 'latin' => 'yuhmilu', 'arti' => 'mengabaikan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'أَطَاعَ', 'latin' => 'athā\'a', 'arti' => 'menaati', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يُطِيْعُ', 'latin' => 'yuthī\'u', 'arti' => 'menaati', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'فَهِمَ', 'latin' => 'fahima', 'arti' => 'memahami', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يَفْهَمُ', 'latin' => 'yafhamu', 'arti' => 'memahami', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'اِهْتَمَّ', 'latin' => 'ihtamma', 'arti' => 'memperhatikan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يَهْتَمُّ', 'latin' => 'yahtammu', 'arti' => 'memperhatikan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'حَثَّ', 'latin' => 'hatstsa', 'arti' => 'menganjurkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يَحُثُّ', 'latin' => 'yaḥutstsu', 'arti' => 'menganjurkan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'تَطَهَّرَ', 'latin' => 'tathahhara', 'arti' => 'bersuci', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يَتَطَهَّرُ', 'latin' => 'yatathahharu', 'arti' => 'bersuci', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'تَوَضَّأَ', 'latin' => 'tawadhdha\'a', 'arti' => 'berwudu', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يَتَوَضَّأُ', 'latin' => 'yatawadhdha\'u', 'arti' => 'berwudu', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'تَجَوَّلَ', 'latin' => 'tajawwala', 'arti' => 'jalan-jalan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يَتَجَوَّلُ', 'latin' => 'yatajawwalu', 'arti' => 'jalan-jalan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'سَقَى', 'latin' => 'saqā', 'arti' => 'menyirami', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يَسْقِي', 'latin' => 'yasqī', 'arti' => 'menyirami', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'بَرَّ', 'latin' => 'barra', 'arti' => 'berbakti', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يَبَرُّ', 'latin' => 'yabarru', 'arti' => 'berbakti', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'شَاهَدَ', 'latin' => 'syāhada', 'arti' => 'menyaksikan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'يُشَاهِدُ', 'latin' => 'yusyāhidu', 'arti' => 'menyaksikan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'رَمْيُ الزُّبَالَةِ', 'latin' => 'ramyuz zubālah', 'arti' => 'membuang sampah', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'النَّهْرُ', 'latin' => 'an-nahr', 'arti' => 'sungai', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'الْفَيَضَانُ', 'latin' => 'al-fayadhān', 'arti' => 'banjir', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'الْكَارِثَةُ', 'latin' => 'al-kāritsah', 'arti' => 'bencana', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'مَنْفَعَةٌ', 'latin' => 'manfa\'ah', 'arti' => 'manfaat', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'مِكْنَسَةٌ', 'latin' => 'miknasah', 'arti' => 'sapu', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'ثَوْبٌ', 'latin' => 'tsaub', 'arti' => 'pakaian', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'أَفْضَلُ', 'latin' => 'afdhal', 'arti' => 'lebih baik', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'أَمْوَحُ', 'latin' => 'amwaḥ', 'arti' => 'lebih nyaman', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'مَسْؤُوْلِيَّةٌ', 'latin' => 'mas\'ūliyyah', 'arti' => 'tanggung jawab', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'الْحُكُوْمَةُ', 'latin' => 'al-ḥukūmah', 'arti' => 'pemerintah', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'رِجَالُ الْقَرْيَةِ', 'latin' => 'rijālul qaryah', 'arti' => 'pemuda desa', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'الْجَمَالَةُ', 'latin' => 'al-jamālah', 'arti' => 'keindahan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'أَمْرٌ', 'latin' => 'amr', 'arti' => 'perintah', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'الْحَيَاةُ الْيَوْمِيَّةُ', 'latin' => 'al-ḥayātul yaumiyyah', 'arti' => 'kehidupan sehari-hari', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'الْحَدَثُ الْأَصْغَرُ', 'latin' => 'al-ḥadatsul ashghar', 'arti' => 'hadas kecil', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'الْمَنْزِلُ', 'latin' => 'al-manzil', 'arti' => 'rumah', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'شَرْطٌ', 'latin' => 'syarth', 'arti' => 'syarat', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'الْوَسَخُ', 'latin' => 'al-wasakh', 'arti' => 'kotoran', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'نَشَاطٌ', 'latin' => 'nasyāth', 'arti' => 'kegiatan', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            ['arab' => 'وَلَدٌ مُطِيْعٌ', 'latin' => 'waladun muthī\'', 'arti' => 'anak yang taat', 'jenis' => 'Mufrad', 'kelas' => 'IX', 'bab' => 6],
            // VIII Bab 1 - Ad-Darsul Awwal (Waktu)
            ['arab' => 'السَّاعَةُ', 'latin' => 'as-saa\'atu', 'arti' => 'jam', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'سَاعَةُ الْيَدِ', 'latin' => 'saa\'atul yad', 'arti' => 'jam tangan', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'سَاعَةُ الْجِدَارِ', 'latin' => 'saa\'atul jidaar', 'arti' => 'jam dinding', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'سَاعَةُ الْمَكْتَبِ', 'latin' => 'saa\'atul maktab', 'arti' => 'jam meja', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'فِي أَيِّ سَاعَةٍ', 'latin' => 'fii ayyi saa\'ah', 'arti' => 'pada jam berapa', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'كَمِ السَّاعَةُ', 'latin' => 'kamis saa\'ah', 'arti' => 'jam berapa', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'السَّاعَةُ الْوَاحِدَةُ', 'latin' => 'as-saa\'atul waahidah', 'arti' => 'jam satu', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'السَّاعَةُ الثَّانِيَةُ', 'latin' => 'as-saa\'atuts tsaaniyah', 'arti' => 'jam dua', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'السَّاعَةُ الثَّالِثَةُ', 'latin' => 'as-saa\'atuts tsaalitsah', 'arti' => 'jam tiga', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'السَّاعَةُ الرَّابِعَةُ', 'latin' => 'as-saa\'aturraabi\'ah', 'arti' => 'jam empat', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'السَّاعَةُ الْخَامِسَةُ', 'latin' => 'as-saa\'atul khaamisah', 'arti' => 'jam lima', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'السَّاعَةُ السَّادِسَةُ', 'latin' => 'as-saa\'atus saadisah', 'arti' => 'jam enam', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'السَّاعَةُ السَّابِعَةُ', 'latin' => 'as-saa\'atus saabi\'ah', 'arti' => 'jam tujuh', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'السَّاعَةُ الثَّامِنَةُ', 'latin' => 'as-saa\'atuts tsaaminah', 'arti' => 'jam delapan', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'السَّاعَةُ التَّاسِعَةُ', 'latin' => 'as-saa\'atut taasi\'ah', 'arti' => 'jam sembilan', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'السَّاعَةُ الْعَاشِرَةُ', 'latin' => 'as-saa\'atul \'aasyirah', 'arti' => 'jam sepuluh', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'السَّاعَةُ الْحَادِيَةَ عَشْرَةَ', 'latin' => 'as-saa\'atul haadiyata \'asyarah', 'arti' => 'jam sebelas', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'السَّاعَةُ الثَّانِيَةَ عَشْرَةَ', 'latin' => 'as-saa\'atuts tsaaniyata \'asyarah', 'arti' => 'jam dua belas', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'دَقِيْقَةٌ', 'latin' => 'daqiiqatun', 'arti' => 'menit', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'نِصْفُ', 'latin' => 'nishfu', 'arti' => 'setengah/30 menit', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'رُبْعُ', 'latin' => 'rub\'u', 'arti' => 'seperempat/15 menit', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'وَ', 'latin' => 'wa', 'arti' => 'lebih', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'إِلَّا', 'latin' => 'illaa', 'arti' => 'kurang', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'كَمْ', 'latin' => 'kam', 'arti' => 'berapa', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'مَتَى', 'latin' => 'mataa', 'arti' => 'kapan', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'وَقْتُ', 'latin' => 'waqtu', 'arti' => 'waktu', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'الْآنَ', 'latin' => 'al-aana', 'arti' => 'sekarang', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'غَدًا', 'latin' => 'ghadan', 'arti' => 'besok', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'قَبْلَ', 'latin' => 'qabla', 'arti' => 'sebelum', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'بَعْدَ', 'latin' => 'ba\'da', 'arti' => 'sesudah', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'يَوْمٌ', 'latin' => 'yaumun', 'arti' => 'hari', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'شَهْرٌ', 'latin' => 'syahrun', 'arti' => 'bulan', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'سَنَةٌ', 'latin' => 'sanatun', 'arti' => 'tahun', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'تَارِيْخٌ', 'latin' => 'taarikhun', 'arti' => 'tanggal', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'تَمَامًا', 'latin' => 'tamaaman', 'arti' => 'tepat, sempurna', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'لَيْلًا', 'latin' => 'lailan', 'arti' => 'malam', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'مَسَاءً', 'latin' => 'masaa\'an', 'arti' => 'sore', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'صَبَاحًا', 'latin' => 'shobaahan', 'arti' => 'pagi', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            ['arab' => 'نَهَارًا', 'latin' => 'nahaaran', 'arti' => 'siang', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 1],
            // VIII Bab 2 - Ad-Darsuts Tsalits (Hobi)
            ['arab' => 'قِرَاءَةٌ', 'latin' => 'qiraa\'ah', 'arti' => 'membaca', 'jenis' => 'Masdar', 'kelas' => 'VIII', 'bab' => 2],
            ['arab' => 'كِتَابَةٌ', 'latin' => 'kitaabah', 'arti' => 'menulis', 'jenis' => 'Masdar', 'kelas' => 'VIII', 'bab' => 2],
            ['arab' => 'رَسْمٌ', 'latin' => 'rasmun', 'arti' => 'menggambar', 'jenis' => 'Masdar', 'kelas' => 'VIII', 'bab' => 2],
            ['arab' => 'سِبَاحَةٌ', 'latin' => 'sibaahah', 'arti' => 'berenang', 'jenis' => 'Masdar', 'kelas' => 'VIII', 'bab' => 2],
            ['arab' => 'صَيْدٌ', 'latin' => 'shaidun', 'arti' => 'memancing', 'jenis' => 'Masdar', 'kelas' => 'VIII', 'bab' => 2],
            // VIII Bab 3 - Ad-Darsuts Tsani (Aktivitas Harian)
            ['arab' => 'أُصَلِّي', 'latin' => 'ushallii', 'arti' => 'aku shalat', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'أَذْهَبُ', 'latin' => 'adzhabu', 'arti' => 'aku pergi', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'تَطْبَخُ', 'latin' => 'tathbakhu', 'arti' => 'dia (perempuan) memasak', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'تَقْرَأُ', 'latin' => 'taqra\'u', 'arti' => 'dia (perempuan) membaca', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'يَتَعَلَّمُ', 'latin' => 'yata\'allamu', 'arti' => 'dia (laki-laki) belajar', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'أَتَنَاوَلُ', 'latin' => 'atanaawalu', 'arti' => 'aku menyantap (makan)', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'أُذَاكِرُ', 'latin' => 'udzaakiru', 'arti' => 'aku mengulang pelajaran', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'تُسَاعِدُ', 'latin' => 'tusaa\'idu', 'arti' => 'dia (perempuan) membantu', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'فِي الْغُرْفَةِ', 'latin' => 'fil ghurfah', 'arti' => 'di dalam kamar', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'أَقُوْمُ', 'latin' => 'aquumu', 'arti' => 'aku bangun', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'جَمَاعَةً', 'latin' => 'jamaa\'atan', 'arti' => 'berjamaah', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'تُرَبِّي', 'latin' => 'turabbii', 'arti' => 'dia (perempuan) mendidik/merawat', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'يَرْجِعُ', 'latin' => 'yarji\'u', 'arti' => 'dia (laki-laki) kembali/pulang', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'نُذَاكِرُ', 'latin' => 'nudzaakiru', 'arti' => 'kami mengulang pelajaran', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'اِسْتَعَدَّ', 'latin' => 'ista\'adda', 'arti' => 'dia (laki-laki) bersiap-siap', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'كَذَلِكَ', 'latin' => 'kadzaalika', 'arti' => 'demikian juga', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'بِالْأَدَوَاتِ الْمَدْرَسِيَّةِ', 'latin' => 'bil-adawaatil madrasiyyah', 'arti' => 'dengan peralatan sekolah', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'قَبْلَ الذِّهَابِ', 'latin' => 'qabladz dzahaab', 'arti' => 'sebelum pergi/berangkat', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'أُسْرَتِي', 'latin' => 'usratii', 'arti' => 'keluargaku', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'نَنَامُ', 'latin' => 'nanaamu', 'arti' => 'kami tidur', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'تُرَافِقُ', 'latin' => 'turaafiqu', 'arti' => 'dia (perempuan) menemani', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'اِقْرَأْ', 'latin' => 'iqra\'', 'arti' => 'bacalah!', 'jenis' => 'Fi\'il Amr', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'أَدْرُسُ', 'latin' => 'adrusu', 'arti' => 'aku belajar', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VIII', 'bab' => 3],
            ['arab' => 'وَغَيْرُهَا', 'latin' => 'wa ghairuhaa', 'arti' => 'dan lain-lainnya', 'jenis' => 'Mufrad', 'kelas' => 'VIII', 'bab' => 3],
            // VII Bab 1 - At-Ta\'aruf (Perkenalan)
            ['arab' => 'حَيٌّ', 'latin' => 'hayyun', 'arti' => 'kompleks', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'جَارٌ', 'latin' => 'jaarun', 'arti' => 'tetangga', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'تَسْكُنُ', 'latin' => 'taskunu', 'arti' => 'kamu (laki-laki) tinggal', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'تَدْرُسُ', 'latin' => 'tadrusu', 'arti' => 'kamu (laki-laki) belajar', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'مِنْ أَيْنَ جِئْتَ', 'latin' => 'min aina ji\'ta', 'arti' => 'dari mana asalmu (laki-laki)', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'جِئْتُ', 'latin' => 'ji\'tu', 'arti' => 'aku berasal', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'عَاصِمَةٌ', 'latin' => '\'aashimatun', 'arti' => 'ibu kota', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'جَدِيْدٌ', 'latin' => 'jadiidun', 'arti' => 'baru', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'سَعِيْدٌ بِمَعْرِفَتِكَ', 'latin' => 'sa\'iidun bima\'rifatika', 'arti' => 'senang berkenalan denganmu (laki-laki)', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'مَسَاءُ الْخَيْرِ', 'latin' => 'masaa\'ul khair', 'arti' => 'selamat sore', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'مَسَاءُ النُّوْرِ', 'latin' => 'masaa\'un nuur', 'arti' => 'selamat sore juga', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'لَدَيَّ', 'latin' => 'ladayya', 'arti' => 'aku memiliki', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'صَدِيْقٌ', 'latin' => 'shadiiqun', 'arti' => 'teman', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'جَزِيْرَةُ سُوْلاَوِيْسِيْ', 'latin' => 'jaziiratu suulaawiisii', 'arti' => 'Pulau Sulawesi', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'وَقَعَتْ', 'latin' => 'waqa\'at', 'arti' => 'letak', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'مَا اسْمُكَ', 'latin' => 'maa ismuka', 'arti' => 'siapa namamu (laki-laki)', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'جِنْسِيَّةٌ', 'latin' => 'jinsiyyatun', 'arti' => 'kewarganegaraan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'مَسْرُوْرٌ بِلِقَائِكَ', 'latin' => 'masruurun biliqaa\'ika', 'arti' => 'senang berjumpa denganmu (laki-laki)', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'أَمَلٌ', 'latin' => 'amalun', 'arti' => 'cita-cita', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'وَلِيُّ الْفَصْلِ', 'latin' => 'waliyyul fashli', 'arti' => 'wali kelas', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'أَجْمَلُ', 'latin' => 'ajmalu', 'arti' => 'paling indah/paling bagus', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'بِيَقِيْنٍ', 'latin' => 'biyaqiinin', 'arti' => 'dengan yakin/dengan percaya diri', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'يَوْمٌ أَوَّلٌ', 'latin' => 'yaumun awwalun', 'arti' => 'hari pertama', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'تُنَادُوْنَنِيْ', 'latin' => 'tunaaduunanii', 'arti' => 'kalian memanggilku', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'تَعَلُّمٌ', 'latin' => 'ta\'allumun', 'arti' => 'belajar', 'jenis' => 'Masdar', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'اِنْتَقَلَ', 'latin' => 'intaqala', 'arti' => 'pindah', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'يَنْتَقِلُ', 'latin' => 'yantaqilu', 'arti' => 'pindah', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'قَامَ', 'latin' => 'qaama', 'arti' => 'berdiri', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'يَقُوْمُ', 'latin' => 'yaquumu', 'arti' => 'berdiri', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'أَدَارَ', 'latin' => 'adaara', 'arti' => 'mengurus', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'يُدِيْرُ', 'latin' => 'yudiiru', 'arti' => 'mengurus', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'عَرَّفَ', 'latin' => '\'arrafa', 'arti' => 'memperkenalkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 1],
            ['arab' => 'يُعَرِّفُ', 'latin' => 'yu\'arrifu', 'arti' => 'memperkenalkan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 1],
            // VII Bab 2 - Al-Marafiq Al-Madrasiyah (Fasilitas Sekolah)
            ['arab' => 'مِقْيَاسُ ضَغْطِ الدَّمِ', 'latin' => 'miqyaasu daghtid dam', 'arti' => 'tensimeter', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'مَقْصَفٌ', 'latin' => 'maqsafun', 'arti' => 'kantin', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'قَاعَةٌ', 'latin' => 'qaa\'atun', 'arti' => 'aula', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'مَكْتَبَةٌ', 'latin' => 'maktabatun', 'arti' => 'perpustakaan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'مُخْتَلِفَةٌ', 'latin' => 'mukhtalifatun', 'arti' => 'berbeda', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'وَظِيْفَةٌ', 'latin' => 'wazhiifatun', 'arti' => 'fungsi', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'الْمَرَافِقُ', 'latin' => 'al-maraafiqu', 'arti' => 'fasilitas', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'غُرْفَةُ الْمُدَرِّسِيْنَ', 'latin' => 'ghurfatul mudarrisiin', 'arti' => 'ruang guru', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'غُرْفَةُ الصِّحَّةِ', 'latin' => 'ghurfatus shihhah', 'arti' => 'ruang kesehatan/UKS', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'حِصَّةٌ دِرَاسِيَّةٌ', 'latin' => 'hishshatun diraasiyyah', 'arti' => 'jam pelajaran', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'مُكَيِّفُ الْهَوَاءِ', 'latin' => 'mukayyiful hawaa\'', 'arti' => 'air conditioner', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'مَيْدَانٌ', 'latin' => 'maidaanun', 'arti' => 'lapangan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'مَعْمَلٌ', 'latin' => 'ma\'malun', 'arti' => 'laboratorium', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'مِقْيَاسُ الْحَرَارَةِ', 'latin' => 'miqyaasul haraarah', 'arti' => 'termometer', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'غُرْفَةُ الشُّؤُوْنِ الْإِدَارِيَّةِ', 'latin' => 'ghurfatusy syu\'uunil idaariyyah', 'arti' => 'ruang tata usaha', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'أَبْصَرَ', 'latin' => 'abshara', 'arti' => 'memperlihatkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'يَجُوْلُ', 'latin' => 'yajuulu', 'arti' => 'berkeliling', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'دَلَّ', 'latin' => 'dalla', 'arti' => 'menunjukkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'مُمَارَسَةٌ', 'latin' => 'mumaarasatun', 'arti' => 'praktik/melakukan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            ['arab' => 'الْأَدَاةُ', 'latin' => 'al-adaatu', 'arti' => 'alat', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            // VII Bab 3 - Al-Adawat Al-Madrasiyah (Peralatan Sekolah)
            ['arab' => 'قَلَمُ السَّبُّوْرَةِ', 'latin' => 'qalamus sabbuurah', 'arti' => 'spidol papan tulis', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'مُعْجَمٌ', 'latin' => 'mu\'jamun', 'arti' => 'kamus', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'صُوَرُ أَبْطَالٍ', 'latin' => 'suwaru abthaalin', 'arti' => 'gambar pahlawan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'طَلاَّسَةٌ', 'latin' => 'thallaasatun', 'arti' => 'penghapus papan tulis', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'أَدَوَاتُ الدِّرَاسَةِ', 'latin' => 'adawaatud diraasah', 'arti' => 'perangkat belajar', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'مُكَيِّفُ هَوَاءٍ', 'latin' => 'mukayyifu hawaa\'in', 'arti' => 'air conditioner/AC', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'حِبْرٌ', 'latin' => 'hibrun', 'arti' => 'tinta', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'خَرِيْطَةٌ', 'latin' => 'khariithatun', 'arti' => 'peta', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'خِزَانَةٌ', 'latin' => 'khizaanatun', 'arti' => 'lemari', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'بُرُوْجِكْتُرْ', 'latin' => 'buruujiktur', 'arti' => 'proyektor', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'كُرَةٌ أَرْضِيَّةٌ', 'latin' => 'kuratun ardhiyyah', 'arti' => 'globe', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'مَوْسُوْعَةٌ', 'latin' => 'mausuu\'atun', 'arti' => 'ensiklopedia', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'حَقِيْبَةٌ زَرْقَاءُ', 'latin' => 'haqiibatun zarqaa\'u', 'arti' => 'tas biru', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'مِقْلَمَةٌ حَمْرَاءُ', 'latin' => 'miqlamatun hamraa\'u', 'arti' => 'wadah pensil merah', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'زِيٌّ', 'latin' => 'ziyyun', 'arti' => 'seragam', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'مِسْطَرَةٌ', 'latin' => 'mistharatun', 'arti' => 'penggaris', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'مِبْرَاةٌ', 'latin' => 'mibraatun', 'arti' => 'rautan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'الْأَدَوَاتُ الْمَدْرَسِيَّةُ', 'latin' => 'al-adawaatul madrasiyyah', 'arti' => 'peralatan sekolah', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'دُكَّانٌ', 'latin' => 'dukkaanun', 'arti' => 'toko', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'بِجَيِّدٍ', 'latin' => 'bijayyidin', 'arti' => 'dengan baik', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'مِمْحَاةٌ', 'latin' => 'mimhaatun', 'arti' => 'karet penghapus', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'مَكَانُهَا', 'latin' => 'makaanuhaa', 'arti' => 'tempatnya', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'جَوْرَبٌ', 'latin' => 'jaurabun', 'arti' => 'kaus kaki', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'حِذَاءٌ', 'latin' => 'hidzaa\'un', 'arti' => 'sepatu', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'كُرَّاسَةٌ', 'latin' => 'kurraasatun', 'arti' => 'buku tulis', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'رَتَّبَ', 'latin' => 'rattaba', 'arti' => 'merapikan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 3],
            ['arab' => 'يُرَتِّبُ', 'latin' => 'yurattibu', 'arti' => 'merapikan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 3],
            // VII Bab 1 - At-Ta\'aruf (Perkenalan)
            // VII Bab 2 - Al-Marafiq Al-Madrasiyah (Fasilitas Sekolah)
            ['arab' => 'مُكَيَّفُ الْهَوَاءِ', 'latin' => 'mukayyaful hawaa\'', 'arti' => 'air conditioner', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 2],
            // VII Bab 3 - Al-Adawat Al-Madrasiyah (Peralatan Sekolah)
            ['arab' => 'مُكَيَّفُ هَوَاءٍ', 'latin' => 'mukayyafu hawaa\'in', 'arti' => 'air conditioner/AC', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 3],
            // VII Bab 4 - Jamal ath-Thabi\'ah (Keindahan Alam)
            ['arab' => 'لِقَاءٌ', 'latin' => 'liqaa\'un', 'arti' => 'pertemuan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'أُسْرَةٌ كَبِيْرَةٌ', 'latin' => 'usratun kabiiratun', 'arti' => 'keluarga besar', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'عُنْوَانٌ', 'latin' => '\'unwaanun', 'arti' => 'alamat', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'جَاوَى الشَّرْقِيَّةِ', 'latin' => 'jaawasy syarqiyyah', 'arti' => 'Jawa Timur', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'شَارِعٌ', 'latin' => 'syaari\'un', 'arti' => 'jalan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'مَدِيْنَةٌ', 'latin' => 'madiinatun', 'arti' => 'kota', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'كَامِلٌ', 'latin' => 'kaamilun', 'arti' => 'lengkap', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'بَعِيْدٌ', 'latin' => 'ba\'iidun', 'arti' => 'jauh', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'مَنَاظِرُ الْعَالَمِ', 'latin' => 'manaazhirul \'aalam', 'arti' => 'pemandangan alam', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'مَبْنَى', 'latin' => 'mabnaa', 'arti' => 'bangunan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'لِتَسْهِيْلٍ', 'latin' => 'litashiilin', 'arti' => 'untuk memudahkan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'شُرْفَةٌ', 'latin' => 'syurfatun', 'arti' => 'teras', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'جَدٌّ', 'latin' => 'jaddun', 'arti' => 'kakek', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'جَوَّالٌ ذَكِيٌّ', 'latin' => 'jawwaalun dzakiyyun', 'arti' => 'smartphone', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'رَقْمٌ', 'latin' => 'raqmun', 'arti' => 'nomor', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'خَالٌ', 'latin' => 'khaalun', 'arti' => 'paman (saudara laki-laki ibu)', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'الدِّيَانَةُ', 'latin' => 'ad-diyaanatu', 'arti' => 'agama', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'إِلَى أَيِّ مَكَانٍ', 'latin' => 'ilaa ayyi makaanin', 'arti' => 'ke mana pun', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'صُوْرَةٌ', 'latin' => 'shuuratun', 'arti' => 'foto', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'عَادَةً', 'latin' => '\'aadatan', 'arti' => 'biasanya', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'زُمْرَةُ الدَّمِ', 'latin' => 'zumratud dam', 'arti' => 'golongan darah', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'مَحْفَظَةُ النُّقُوْدِ', 'latin' => 'mahfazhatun nuquud', 'arti' => 'dompet', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'تَارِيْخُ الْمِيْلَادِ', 'latin' => 'taarikhul miilaad', 'arti' => 'tanggal lahir', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'عُنْوَانُ الْمَدْرَسَةِ', 'latin' => '\'unwaanul madrasah', 'arti' => 'alamat sekolah', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'مَايُوْ', 'latin' => 'maayuu', 'arti' => 'Mei', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'بِطَاقَةٌ شَخْصِيَّةٌ لِلْأَوْلَادِ', 'latin' => 'bithaaqatun syakhshiyyatun lil-awlaad', 'arti' => 'kartu identitas anak (KIA)', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'سَاكِنٌ', 'latin' => 'saakinun', 'arti' => 'warga', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'الْمَدْرَسَةُ الْمُتَوَسِّطَةُ', 'latin' => 'al-madrasatul mutawassithah', 'arti' => 'sekolah menengah pertama (SMP)', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'وَاجِبٌ مَنْزِلِيٌّ', 'latin' => 'waajibun manziliyyun', 'arti' => 'PR', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'شَخْصِيَّةٌ', 'latin' => 'syakhshiyyatun', 'arti' => 'identitas', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'اِسْمٌ كَامِلٌ', 'latin' => 'ismun kaamilun', 'arti' => 'nama lengkap', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'جِنْسٌ', 'latin' => 'jinsun', 'arti' => 'jenis kelamin', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'زَارَ', 'latin' => 'zaara', 'arti' => 'mengunjungi', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'يَزُوْرُ', 'latin' => 'yazuuru', 'arti' => 'mengunjungi', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'نَظَرَ', 'latin' => 'nazhara', 'arti' => 'melihat', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'يَنْظُرُ', 'latin' => 'yanzhuru', 'arti' => 'melihat', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'غَيَّرَ', 'latin' => 'ghayyara', 'arti' => 'mengganti', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'يُغَيِّرُ', 'latin' => 'yughayyiru', 'arti' => 'mengganti', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'تَقَرَّبَ', 'latin' => 'taqarraba', 'arti' => 'mendekati', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'يَتَقَرَّبُ إِلَى', 'latin' => 'yataqarrabu ilaa', 'arti' => 'mendekati', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'اِتَّصَلَ', 'latin' => 'ittashala', 'arti' => 'menelpon', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'يَتَّصِلُ بِ', 'latin' => 'yattashilu bi', 'arti' => 'menelpon', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'بَيَّنَ', 'latin' => 'bayyana', 'arti' => 'menjelaskan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 4],
            ['arab' => 'يُبَيِّنُ', 'latin' => 'yubayyinu', 'arti' => 'menjelaskan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 4],
            // VII Bab 5 - Khaliq al-\'Alam (Pencipta Alam)
            ['arab' => 'غُرْفَةُ الْجُلُوْسِ', 'latin' => 'ghurfatul juluus', 'arti' => 'ruang santai', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'صُوْرَةٌ مُلَوَّنَةٌ', 'latin' => 'shuuratun mulawwanatun', 'arti' => 'lukisan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'أَدَاةٌ', 'latin' => 'adaatun', 'arti' => 'perabot', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'غُرْفَةُ الْمُذَاكَرَةِ', 'latin' => 'ghurfatul mudzaakarah', 'arti' => 'ruang belajar', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'رَفُّ الْكُتُبِ', 'latin' => 'raffful kutub', 'arti' => 'rak buku', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'الْمِرْحَاضُ', 'latin' => 'al-mirhaadhu', 'arti' => 'toilet', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'سَجَّادَةٌ', 'latin' => 'sajjaadatun', 'arti' => 'karpet', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'غُرْفَةُ الْاِسْتِقْبَالِ', 'latin' => 'ghurfatul istiqbaal', 'arti' => 'ruang tamu', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'مَعْجُوْنٌ', 'latin' => 'ma\'juunun', 'arti' => 'pasta gigi', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'غُرْفَةٌ', 'latin' => 'ghurfatun', 'arti' => 'ruangan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'مَطْبَخٌ', 'latin' => 'mathbakhun', 'arti' => 'dapur', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'التِّلْفَازُ', 'latin' => 'at-tilfaazu', 'arti' => 'televisi', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'مِقْلًى', 'latin' => 'miqlan', 'arti' => 'wajan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'أَرِيْكَةٌ', 'latin' => 'ariikatun', 'arti' => 'sofa', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'الْكَرَاجُ', 'latin' => 'al-karaaju', 'arti' => 'garasi', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'مِنْضَدَةٌ', 'latin' => 'mindhadatun', 'arti' => 'meja tamu', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'ثَلَّاجَةٌ', 'latin' => 'tsallaajatun', 'arti' => 'kulkas', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'فُرْشَةُ الْأَسْنَانِ', 'latin' => 'fursyatul asnaan', 'arti' => 'sikat gigi', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'مِنْشَفَةٌ', 'latin' => 'minsyafatun', 'arti' => 'handuk', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'غَسَّالَةٌ', 'latin' => 'ghassaalatun', 'arti' => 'mesin cuci', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'مَكْتَبُ التَّعَلُّمِ', 'latin' => 'maktabut ta\'allum', 'arti' => 'meja belajar', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'مَسْحُوْقُ الْغَسِيْلِ', 'latin' => 'mashuuqul ghasiil', 'arti' => 'detergen', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'مِلْحٌ', 'latin' => 'milhun', 'arti' => 'garam', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'تَابِلٌ', 'latin' => 'taabilun', 'arti' => 'bumbu', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'حَوْلَ', 'latin' => 'haula', 'arti' => 'di sekitar', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'عَصِيْرٌ', 'latin' => '\'ashiirun', 'arti' => 'jus', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'رَفٌّ', 'latin' => 'raffun', 'arti' => 'rak', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'مِلْعَقَةٌ', 'latin' => 'mil\'aqatun', 'arti' => 'sendok', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'كُوْبٌ', 'latin' => 'kuubun', 'arti' => 'gelas', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'حَاجَةٌ أَسَاسِيَّةٌ', 'latin' => 'haajatun asaasiyyatun', 'arti' => 'kebutuhan primer', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'حَدِيْقَةٌ', 'latin' => 'hadiiqatun', 'arti' => 'taman', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'الضَّيْفُ', 'latin' => 'adh-dhaifu', 'arti' => 'tamu', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'مِرْوَحَةٌ', 'latin' => 'mirwahatun', 'arti' => 'kipas angin', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'بِرْكَةُ السَّمَكِ', 'latin' => 'birkatus samak', 'arti' => 'kolam ikan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'مَوْقِدٌ', 'latin' => 'mauqidun', 'arti' => 'kompor', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'وِسَادَةٌ', 'latin' => 'wisaadatun', 'arti' => 'bantal', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'مُلَوَّنَةٌ', 'latin' => 'mulawwanatun', 'arti' => 'berwarna-warni', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'تَعَلَّمَ', 'latin' => 'ta\'allama', 'arti' => 'belajar', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'أَطْعَمَ', 'latin' => 'ath\'ama', 'arti' => 'memberi makan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 5],
            ['arab' => 'يُطْعِمُ', 'latin' => 'yuth\'imu', 'arti' => 'memberi makan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 5],
            // VII Bab 6 - Al-Hifaadz \'ala al-Bi\'ah (Menjaga Lingkungan)
            ['arab' => 'الْخِبْرَةُ الْيَوْمِيَّةُ', 'latin' => 'al-khibratul yaumiyyah', 'arti' => 'pengalaman sehari-hari', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'ثَمِيْنَةٌ', 'latin' => 'tsamiinatun', 'arti' => 'berharga', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'الْغِذَاءُ', 'latin' => 'al-ghidzaa\'u', 'arti' => 'makanan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'خَاصَّةٌ', 'latin' => 'khaashshatun', 'arti' => 'khusus', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'مَا عِنْدِيْ', 'latin' => 'maa \'indii', 'arti' => 'saya tidak punya', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'أُسْتُوْدِيُوْ الرَّقْصِ', 'latin' => 'ustuudiyuur raqsh', 'arti' => 'sanggar tari', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'الْغَدَاءُ', 'latin' => 'al-ghadaa\'u', 'arti' => 'makan siang', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'الْعَادَةُ', 'latin' => 'al-\'aadatu', 'arti' => 'biasa', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'مَوْقِفٌ', 'latin' => 'mauqifun', 'arti' => 'tempat parkir', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'الْبَارِحَةُ', 'latin' => 'al-baarihatu', 'arti' => 'semalam', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'سِوَى', 'latin' => 'siwaa', 'arti' => 'selain', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'الصَّلَاةُ الْمَفْرُوْضَةُ', 'latin' => 'ash-shalaatul mafruudhah', 'arti' => 'salat wajib', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'الرَّقْصُ', 'latin' => 'ar-raqshu', 'arti' => 'menari', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'الزِّيُّ الْمَدْرَسِيُّ', 'latin' => 'az-ziyyul madrasiyyu', 'arti' => 'seragam sekolah', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'نِظَامٌ', 'latin' => 'nizhaamun', 'arti' => 'peraturan', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'حَتَّى', 'latin' => 'hattaa', 'arti' => 'sampai', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'فَرْدٌ', 'latin' => 'fardun', 'arti' => 'orang', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'مُهَنْدِسٌ', 'latin' => 'muhandisun', 'arti' => 'arsitek', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'فَلَّاحَةٌ', 'latin' => 'fallaahatun', 'arti' => 'petani', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'تَنَاوُلُ الْفُطُوْرِ', 'latin' => 'tanaawulul futhuur', 'arti' => 'sarapan pagi', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'مَزْرَعَةٌ', 'latin' => 'mazra\'atun', 'arti' => 'sawah', 'jenis' => 'Mufrad', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'يَسْقِيْ', 'latin' => 'yasqii', 'arti' => 'menyiram', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'اِسْتَيْقَظَ', 'latin' => 'istaiqazha', 'arti' => 'bangun tidur', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'يَسْتَيْقِظُ', 'latin' => 'yastaiqizhu', 'arti' => 'bangun tidur', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'تَيَقَّنَ', 'latin' => 'tayaqqana', 'arti' => 'yakin', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'يَتَيَقَّنُ', 'latin' => 'yatayaqqanu', 'arti' => 'yakin', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'وَقَفَ', 'latin' => 'waqafa', 'arti' => 'berhenti', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'يَقِفُ', 'latin' => 'yaqifu', 'arti' => 'berhenti', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'اِلْتَقَى', 'latin' => 'iltaqaa', 'arti' => 'bertemu', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'يَلْتَقِيْ', 'latin' => 'yaltaqii', 'arti' => 'bertemu', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'اِتَّجَهَ', 'latin' => 'ittajaha', 'arti' => 'berjalan menuju', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'يَتَّجِهُ', 'latin' => 'yattajihu', 'arti' => 'berjalan menuju', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'عَمِلَ', 'latin' => '\'amila', 'arti' => 'mengerjakan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'يَعْمَلُ', 'latin' => 'ya\'malu', 'arti' => 'mengerjakan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'أَعَدَّ', 'latin' => 'a\'adda', 'arti' => 'menyiapkan', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'يُعِدُّ', 'latin' => 'yu\'iddu', 'arti' => 'menyiapkan', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'تَكَوَّنَ', 'latin' => 'takawwana', 'arti' => 'terdiri atas', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'يَتَكَوَّنُ عَلَى', 'latin' => 'yatakawwanu \'alaa', 'arti' => 'terdiri atas', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'اِسْتَحَمَّ', 'latin' => 'istahamma', 'arti' => 'mandi', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'يَسْتَحِمُّ', 'latin' => 'yastahimmu', 'arti' => 'mandi', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'طَبَخَ', 'latin' => 'thabakha', 'arti' => 'memasak', 'jenis' => 'Fi\'il Madhi', 'kelas' => 'VII', 'bab' => 6],
            ['arab' => 'يَطْبُخُ', 'latin' => 'yathbukhu', 'arti' => 'memasak', 'jenis' => 'Fi\'il Mudhari\'', 'kelas' => 'VII', 'bab' => 6],
        ];

        $now = now();
        foreach (array_chunk($data, 200) as $chunk) {
            DB::table('mufrodats')->insert(array_map(
                fn($r) => $r + ['created_at' => $now, 'updated_at' => $now],
                $chunk
            ));
        }
    }
}
